
required = [
	# go-assets-builder https://github.com/jessevdk/go-assets-builder
	"github.com/jessevdk/go-assets-builder"
]

[[constraint]]
  name = "github.com/beito123/binary"
  branch = "master"

[[constraint]]
  name = "github.com/beito123/nbt"
  version = "1.2.1"

[[constraint]]
  name = "github.com/beito123/goleveldb"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
